---
  - name: Install dependencies
    ansible.builtin.apt:
      pkg:
        - mysql-server
        - python3-pymysql
      state: latest
      update_cache: yes
    become: true
    
  - name: restart service mysql
    ansible.builtin.shell:
      cmd: service mysql restart
    become: true

  - name: Create a new database with name "{{ wp_db_name }}"
    community.mysql.mysql_db:
      name: "{{ wp_db_name }}"
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
    become: true
    notify: 
      - restart mysql
    

  - name: Create database user with name "{{ wp_db_user }}" and password "{{ wp_db_pass }}" with all database privileges
    community.mysql.mysql_user:
      name: "{{ wp_db_user }}"
      password: "{{ wp_db_pass }}"
      priv: "{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
      host: "{{ item }}"
    with_items:
    - "localhost"
    - "127.0.0.1"
    - "{{ wp_ip }}"
    become: true

  - name: Configure database
    ansible.builtin.replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: "127.0.0.1"
      replace: "0.0.0.0"
    become: true
    notify: 
      - restart mysql
